### ISSUE TITLE
How to make it work on windows with xampp

### ISSUE THREAD

**Issue by practicetestsforall** [Akshat4112/SchoolErp#12]
I extracted the files to htdocs and imported the school_erp.sql, found in the extracted files, into the school_erp database that I created in myphpadmin. I opened the admin table in the database and checked the credentials, used all of them to try to log in at localhost but none worked. 404 page not found. What am I doing wrong? Please help. Thanks.

**Comment by Akshat4112** [comment]
Please Change the directory name in the .htaccess file in root directory according to your directory name.

**Comment by xanny69** [comment]
I fixed this issue:
the issue was about the port80.
Solution: there are two ways actually!
1) Disabling the access of port  80 to other apps:
Go to CMD(Admin Mode)->net stop http
press Y.
Open Apache in port 80 (The default one)
//////////////////////////////////////////////////
2) Changing the Default Port of the Porject.
tbh, I really dont know how to do that. Even by changing the listening port of httpconfg of the apache does not work because when you login with correct Credentials, it redirects to port 80...

**Comment by AbhishekDere** [comment]
> 
> 
> Please Change the directory name in the .htaccess file in root directory according to your directory name.

Please give an example because over here, even after changing the htaccess to correct directory, it still shows 404 on every page clicked

**Comment by NimrodJMoyo** [comment]
<IfModule mod_rewrite.c>
 RewriteEngine On
 #rename "codeIgniter213" with your application directory
 #For example you rename the entire CodeIgniter application as "mysite"
 #then, the "RewriteBase /" will be like this "RewriteBase /mysite"
 #same as at line number 10, "RewriteRule ^(.*)$ /codeIgniter213/index.php #/$1 [L]" will be like this "RewriteRule ^(.*)$ /mysite/index.php/$1 [L]"

 RewriteBase /example_directory_folder_name
 RewriteCond %{REQUEST_FILENAME} !-f
 RewriteCond %{REQUEST_FILENAME} !-d
 RewriteRule ^(.*)$ /example_directory_folder_name/index.php/$1 [L]
</IfModule>

**Comment by Islamic-Blogger** [comment]
complicated

**Comment by huclilu** [comment]
> complicated
The last line of. htaccess file is modified as：
RewriteRule ^(.*)$ /SchoolERP/index.php?$1 [L]

like me：


<IfModule mod_rewrite.c>
 RewriteEngine On
 #rename "codeIgniter213" with your application directory
 #For example you rename the entire CodeIgniter application as "mysite"
 #then, the "RewriteBase /" will be like this "RewriteBase /mysite"
 #same as at line number 10, "RewriteRule ^(.*)$ /codeIgniter213/index.php #/$1 [L]" will be like this "RewriteRule ^(.*)$ /mysite/index.php/$1 [L]"

 RewriteBase /SchoolERP
 RewriteCond %{REQUEST_FILENAME} !-f
 RewriteCond %{REQUEST_FILENAME} !-d
 RewriteRule ^(.*)$ /SchoolERP/index.php?$1 [L]
</IfModule>
